//HERE I HAVE DEFINED THE CONSTANTS WHICH WILL BE USED IN ACTIONS
export const actionTypes = {
    SET_PRODUCT: "SET_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT", 
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_USER: "SET_USER",
    ACTIVE_USER: "ACTIVE_USER",
    REMOVE_ACTIVE_USER: "REMOVE_ACTIVE_USER",
    ADD_TO_BAG: "ADD_TO_BAG",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    RESET:"RESET",
    
}