//HERE I HAVE DEFINED THE CONSTANTS WHICH WILL BE USED IN ACTIONS

export const actionTypes = {
    SET_PRODUCT: "SET_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT", 
    REGISTER_USER:"REGISTER_USER",
}